---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: "{{ nexus_become }}"

- name: Restart nexus
  ansible.builtin.systemd:
    name: "{{ nexus_service_name }}"
    state: restarted
  become: "{{ nexus_become }}"
