---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: nexus-el9
    image: rockylinux:9
    command: /usr/sbin/init
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  inventory:
    group_vars:
      all:
        nexus_wait_for_start: false
verifier:
  name: ansible
